/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/girl.glb 
Author: 腱鞘炎の人 (https://sketchfab.com/Kensyouen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/just-a-girl-b2359160a4f54e76b5ae427a55d9594d
Title: Just a girl
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Girl(props) {
  const { nodes, materials } = useGLTF('./models/Girl.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/Girl.glb')
